import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { studioRequest } from "../lib/studioApi";

type Field = { name: string; type: string; values?: string[] };
type Meta = { name: string; label: string; profile?: boolean; subscriberField?: string; emailField?: string; phoneField?: string; fields: Field[] };
type Leaf = { kind: "CONDITION"; leftAlias: string; leftField: string; leftTransform?: string; leftTransformArgument?: string; operator: string; rightKind: "VALUE" | "FIELD"; rightAlias: string; rightField: string; value: string; valueTo?: string; relativeUnit?: string; field?: string };
type Group = { kind: "GROUP"; logic: string; items: any[] };
type Option = { value: string; label: string };

const leaf = (): Leaf => ({ kind: "CONDITION", leftAlias: "profile", leftField: "", operator: "EQUALS", rightKind: "VALUE", rightAlias: "profile", rightField: "", value: "", valueTo: "", relativeUnit: "DAYS" });
const group = (items: Array<Leaf | Group> = []): Group => ({ kind: "GROUP", logic: "AND", items });
const normalizeGroup = (value: any): Group => value?.kind === "GROUP" ? value : group(Array.isArray(value) ? value.map(({ connector: _connector, ...item }: any) => ({ kind: "CONDITION", ...item })) : []);
const side = (sourceObject = "Individual") => ({ sourceObject, joins: [] as any[], filters: group(), fields: [] as any[], collections: [] as any[], groupBy: [] as any[], having: group() });
const initial = { name: "", description: "", isActive: true, definition: { contactPoints: ["EMAIL"], inclusion: side(), exclusion: { ...side(), enabled: false } } };
const operators: Record<string, string[]> = { string: ["EQUALS", "NOT_EQUALS", "CONTAINS", "STARTS_WITH", "ENDS_WITH", "IN", "NOT_IN", "IS_NULL", "IS_NOT_NULL"], number: ["EQUALS", "NOT_EQUALS", "GT", "GTE", "LT", "LTE", "BETWEEN", "IN", "NOT_IN", "IS_NULL", "IS_NOT_NULL"], date: ["EQUALS", "BEFORE", "AFTER", "BETWEEN", "IN_LAST", "NOT_IN_LAST", "IS_NULL", "IS_NOT_NULL"], boolean: ["EQUALS", "NOT_EQUALS", "IS_NULL", "IS_NOT_NULL"], enum: ["EQUALS", "NOT_EQUALS", "IN", "NOT_IN", "IS_NULL", "IS_NOT_NULL"] };
const filterFunctions: Record<string, Array<{ value: string; label: string; argument?: string }>> = { string: [{ value: "NONE", label: "No function" }, { value: "UPPER", label: "Uppercase" }, { value: "LOWER", label: "Lowercase" }, { value: "TRIM", label: "Trim spaces" }, { value: "LENGTH", label: "Text length" }, { value: "CONCAT", label: "Add text", argument: "Text to add" }, { value: "SUBSTRING", label: "Extract part", argument: "Start,length" }, { value: "REPLACE", label: "Replace", argument: "Old,new" }], number: [{ value: "NONE", label: "No function" }, { value: "ABS", label: "Absolute" }, { value: "ROUND", label: "Round" }], date: [{ value: "NONE", label: "No function" }, { value: "YEAR", label: "Year" }, { value: "MONTH", label: "Month" }, { value: "DAY", label: "Day" }], boolean: [{ value: "NONE", label: "No function" }], enum: [{ value: "NONE", label: "No function" }] };
const options = (values: string[] | undefined) => (values ?? []).map(value => ({ value, label: value.replaceAll("_", " ") }));
const countConditions = (value: any): number => normalizeGroup(value).items.reduce((sum, item) => sum + (item.kind === "GROUP" ? countConditions(item) : 1), 0);
const friendlySegmentError = (reason: any, action: string) => {
  const message = String(reason?.message ?? "");
  if (/BigInt|serialize/i.test(message)) return `The ${action} contains a numeric value that could not be displayed. Please try again after refreshing.`;
  if (/timeout/i.test(message)) return `The ${action} took too long. Narrow the criteria and try again.`;
  if (/does not exist|not available/i.test(message)) return `The ${action} uses a field or object that is no longer available. Review the highlighted configuration.`;
  return message && !/Invalid .* invocation|at .*\.ts:/i.test(message) ? message : `We could not ${action}. Review the segment configuration and try again.`;
};

export function Select({ value, options: items, onChange, placeholder = "Choose…", disabled = false, compact = false }: { value: string; options: Option[]; onChange: (value: string) => void; placeholder?: string; disabled?: boolean; compact?: boolean }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const selected = items.find(item => item.value === value);
  return <div ref={root} className={`segment-select ${open ? "open" : ""} ${compact ? "compact" : ""}`}>
    <button type="button" className="segment-select-trigger" disabled={disabled} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(!open)}><span className={selected ? "" : "placeholder"}>{selected?.label ?? placeholder}</span><i /></button>
    {open && <div className="segment-select-menu" role="listbox">{items.map(item => <button type="button" role="option" aria-selected={item.value === value} className={item.value === value ? "selected" : ""} key={item.value} onClick={() => { onChange(item.value); setOpen(false); }}>{item.label}{item.value === value && <b>✓</b>}</button>)}</div>}
  </div>;
}

function MultiSelect({ value, options: items, onChange }: { value: string; options: Option[]; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const selected = value.split(",").map(item => item.trim()).filter(Boolean);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const toggle = (item: string) => onChange((selected.includes(item) ? selected.filter(value => value !== item) : [...selected, item]).join(","));
  return <div ref={root} className={`segment-select segment-multiselect ${open ? "open" : ""}`}><button type="button" className="segment-select-trigger" onClick={() => setOpen(!open)}><span className={selected.length ? "" : "placeholder"}>{selected.length ? `${selected.length} selected` : "Choose values…"}</span><i /></button>{open && <div className="segment-select-menu">{items.map(item => <button type="button" className={selected.includes(item.value) ? "selected" : ""} key={item.value} onClick={() => toggle(item.value)}><span className="multi-check">{selected.includes(item.value) ? "✓" : ""}</span>{item.label}</button>)}</div>}</div>;
}

function SegmentsListWithSimulation() {
  const navigate = useNavigate(); const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const [simulation, setSimulation] = useState<any>(); const [generating, setGenerating] = useState(false);
  const load = () => studioRequest<any>("/segments").then(data => setItems(data.items)).catch(reason => setError(reason.message));
  useEffect(() => { void load(); }, []);
  async function remove(item: any) { if (!confirm(`Delete “${item.name}”? Customer data will not be deleted.`)) return; await studioRequest(`/segments/${item.id}`, { method: "DELETE" }); await load(); }
  async function generateSimulation() { if (!confirm("Generate the deterministic segment-testing population? Existing simulation records will not be duplicated.")) return; setGenerating(true); setError(""); try { setSimulation(await studioRequest<any>("/segments/simulation", { method: "POST", body: JSON.stringify({ confirmation: "GENERATE_SEGMENT_TEST_DATA" }) })); } catch (reason: any) { setError(reason.message); } finally { setGenerating(false); } }
  return <section><header className="studio-hero"><div><div className="eyebrow">Audience Studio</div><h1>Segments</h1><p>Build reusable audiences from business data without SQL.</p></div><div className="segment-list-actions"><button className="secondary" disabled={generating} onClick={() => void generateSimulation()}>{generating ? "Generating test population…" : "Generate test population"}</button><button className="primary" onClick={() => navigate("/segments/new")}>+ New segment</button></div></header>{error && <div className="alert error">{error}</div>}{simulation && <div className="alert success simulation-result"><b>Simulation population is ready.</b><span>{Object.entries(simulation).map(([key, value]) => `${value} ${key}`).join(" · ")}</span></div>}<div className="studio-panel tablewrap"><table><thead><tr><th>Name</th><th>Profile source</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><b>{item.name}</b><small className="segment-description">{item.description}</small></td><td>{item.sourceObject}</td><td>{item.isActive ? "Active" : "Inactive"}</td><td>{new Date(item.updatedDate).toLocaleString()}</td><td><button className="secondary" onClick={() => navigate(`/segments/${item.id}`)}>View / edit</button> <button className="danger-button" onClick={() => void remove(item)}>Delete</button></td></tr>)}</tbody></table>{!items.length && <div className="empty-state">No segments yet.</div>}</div></section>;
}

export function SegmentsListPage() {
  const navigate = useNavigate(); const [items, setItems] = useState<any[]>([]); const [error, setError] = useState("");
  const load = () => studioRequest<any>("/segments").then(data => setItems(data.items)).catch(reason => setError(reason.message));
  useEffect(() => { void load(); }, []);
  async function remove(item: any) { if (!confirm(`Delete “${item.name}”? Customer data will not be deleted.`)) return; await studioRequest(`/segments/${item.id}`, { method: "DELETE" }); await load(); }
  return <section><header className="studio-hero"><div><div className="eyebrow">Audience Studio</div><h1>Segments</h1><p>Build reusable audiences from business data without SQL.</p></div><button className="primary" onClick={() => navigate("/segments/new")}>+ New segment</button></header>{error && <div className="alert error">{error}</div>}<div className="studio-panel tablewrap"><table><thead><tr><th>Name</th><th>Profile source</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><b>{item.name}</b><small className="segment-description">{item.description}</small></td><td>{item.sourceObject}</td><td>{item.isActive ? "Active" : "Inactive"}</td><td>{new Date(item.updatedDate).toLocaleString()}</td><td><button className="secondary" onClick={() => navigate(`/segments/${item.id}`)}>View / edit</button> <button className="danger-button" onClick={() => void remove(item)}>Delete</button></td></tr>)}</tbody></table>{!items.length && <div className="empty-state">No segments yet.</div>}</div></section>;
}

export function SegmentBuilderPage() {
  const { id } = useParams(); const navigate = useNavigate(); const location = useLocation(); const generated = (location.state as any)?.generatedSegment; const [form, setForm] = useState<any>(generated ? { ...initial, ...generated, definition: { ...generated.definition, inclusion: normalizeSide(generated.definition.inclusion), exclusion: normalizeSide(generated.definition.exclusion) } } : initial); const [objects, setObjects] = useState<Meta[]>([]); const [profiles, setProfiles] = useState<string[]>([]); const [tab, setTab] = useState<"inclusion" | "exclusion" | "preview">("inclusion"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const [previewing, setPreviewing] = useState(false); const [preview, setPreview] = useState<any>(); const [previewFilters, setPreviewFilters] = useState<Group>(group()); const [page, setPage] = useState(1); const [detailsReady, setDetailsReady] = useState(Boolean(id || generated)); const [detailsOpen, setDetailsOpen] = useState(false);
  useEffect(() => { void Promise.all([studioRequest<any>("/segments/metadata"), id ? studioRequest<any>(`/segments/${id}`) : Promise.resolve(null)]).then(([metadata, saved]) => { setObjects(metadata.objects); setProfiles(metadata.profileObjects); if (saved) setForm({ ...saved, definition: { ...saved.definition, inclusion: normalizeSide(saved.definition.inclusion), exclusion: normalizeSide(saved.definition.exclusion) } }); }).catch(reason => setError(reason.message)); }, [id]);
  const sideKey = tab === "exclusion" ? "exclusion" : "inclusion"; const current = form.definition[sideKey];
  const aliases = useMemo(() => [{ id: "profile", object: current?.sourceObject, label: current?.sourceObject }, ...(current?.joins ?? []).map((join: any) => ({ id: join.id, object: join.object, label: join.object }))], [current]);
  const object = (name: string) => objects.find(item => item.name === name); const aliasFields = (alias: string) => object(aliases.find(item => item.id === alias)?.object ?? "")?.fields ?? [];
  const updateSide = (patch: any) => setForm((old: any) => ({ ...old, definition: { ...old.definition, [sideKey]: { ...old.definition[sideKey], ...patch } } }));
  const updateRow = (key: string, index: number, patch: any) => updateSide({ [key]: current[key].map((row: any, rowIndex: number) => rowIndex === index ? { ...row, ...patch } : row) });
  const source = object(form.definition.inclusion.sourceObject); const subscriberKey = source?.name === "Individual" ? "Individual.id" : `${source?.name}.individualId`;
  async function save() { setError(""); setSaving(true); try { const saved = await studioRequest<any>(id ? `/segments/${id}` : "/segments", { method: id ? "PATCH" : "POST", body: JSON.stringify(form) }); setNotice("Segment saved successfully"); window.setTimeout(() => setNotice(""), 3500); if (!id) navigate(`/segments/${saved.id}`, { replace: true }); } catch (reason: any) { setError(friendlySegmentError(reason, "save this segment")); } finally { setSaving(false); } }
  async function runPreview(nextPage = 1) { setError(""); setPreviewing(true); try { const result = await studioRequest<any>(id ? `/segments/${id}/preview` : "/segments/preview", { method: "POST", body: JSON.stringify({ definition: form.definition, page: nextPage, pageSize: 25, filters: previewFilters }) }); setPreview(result); setPage(nextPage); setTab("preview"); setNotice("Audience preview generated successfully"); window.setTimeout(() => setNotice(""), 3500); } catch (reason: any) { setError(friendlySegmentError(reason, "generate the audience preview")); } finally { setPreviewing(false); } }
  if (!detailsReady) return <SegmentDetailsStep form={form} setForm={setForm} onCancel={() => navigate("/segments")} onNext={() => { if (!form.name.trim()) { setError("Segment name is required."); return; } setError(""); setDetailsReady(true); }} error={error} />;
  return <section className="segment-page"><header className="segment-builder-header"><div><div className="eyebrow">Audience Studio</div><h1>{form.name}</h1><p>{form.description || "No description"}</p></div><div><button className="secondary" onClick={() => setDetailsOpen(true)}>Edit details</button><button className="secondary" onClick={() => navigate("/segments")}>← Segments</button></div></header>{error && <div className="segment-toast error" role="alert"><span>!</span>{error}<button onClick={() => setError("")}>×</button></div>}{notice && <div className="segment-toast success" role="status"><span>✓</span>{notice}<button onClick={() => setNotice("")}>×</button></div>}
    <nav className="segment-tabs">{(["inclusion", "exclusion", "preview"] as const).map(item => <button type="button" key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "preview" ? <PreviewPanel data={preview} value={previewFilters} onChange={setPreviewFilters} run={runPreview} page={page} /> : <div className="segment-layout segment-layout-full"><div className="segment-builder-content">
      {tab === "exclusion" && <section className="studio-panel"><label className="studio-check"><input type="checkbox" checked={current.enabled} onChange={event => updateSide({ enabled: event.target.checked })} /> Enable exclusions</label><p>The source stays locked to {form.definition.inclusion.sourceObject}. Matches are removed using subscriberKey.</p></section>}
      <section className="studio-panel"><Heading number="1" title="Profile source" /><label className="segment-field"><span>Starting profile object</span><Select value={current.sourceObject} disabled={tab === "exclusion"} options={options(profiles)} onChange={sourceObject => setForm((old: any) => ({ ...old, definition: { ...old.definition, inclusion: side(sourceObject), exclusion: { ...side(sourceObject), enabled: old.definition.exclusion.enabled } } }))} /></label><div className="segment-key">Mandatory subscriber key: <b>{subscriberKey}</b></div>{tab === "inclusion" && <div className="contact-points"><b>Contact points</b>{["EMAIL", "PHONE", "WHATSAPP"].map(point => <label key={point}><input type="checkbox" checked={form.definition.contactPoints.includes(point)} onChange={event => setForm({ ...form, definition: { ...form.definition, contactPoints: event.target.checked ? [...form.definition.contactPoints, point] : form.definition.contactPoints.filter((item: string) => item !== point) } })} /><span>{point}</span></label>)}</div>}</section>
      <section className="studio-panel"><Heading number="2" title="Joins" action={<button className="secondary" onClick={() => updateSide({ joins: [...current.joins, { id: `join_${Date.now()}`, object: "PageVisit", type: "LEFT", conditions: group([leaf()]) }] })}>+ Join object</button>} />{current.joins.map((join: any, index: number) => <article className="segment-card" key={join.id}><div className="join-heading"><Select value={join.type} options={options(["LEFT", "INNER"])} onChange={type => updateRow("joins", index, { type })} /><Select value={join.object} options={objects.map(item => ({ value: item.name, label: item.label }))} onChange={joinedObject => updateRow("joins", index, { object: joinedObject, conditions: group([leaf()]) })} /><button className="danger-button" onClick={() => updateSide({ joins: current.joins.filter((_: any, rowIndex: number) => rowIndex !== index) })}>Remove join</button></div><ExpressionGroup value={normalizeGroup(join.conditions)} aliases={aliases} fields={aliasFields} onChange={conditions => updateRow("joins", index, { conditions })} /></article>)}</section>
      <section className="studio-panel"><Heading number="3" title="Audience filters" /><ExpressionGroup value={normalizeGroup(current.filters)} aliases={aliases} fields={aliasFields} onChange={filters => updateSide({ filters })} emptyText="No audience filters. Every profile matching the joins is included." /></section>
      <SeparatedOutputFields current={current} contactPoints={form.definition.contactPoints} aliases={aliases} fields={aliasFields} updateRow={updateRow} updateSide={updateSide} />
    </div></div>}
    <footer className="studio-actions sticky-actions segment-actions"><button className="primary" disabled={saving} onClick={() => void save()}>{saving && <i className="button-spinner" />} {saving ? "Saving…" : "Save segment"}</button><button className="secondary" disabled={previewing} onClick={() => void runPreview(1)}>{previewing && <i className="button-spinner dark" />} {previewing ? "Loading preview…" : "Preview audience"}</button></footer>{detailsOpen && <SegmentDetailsModal form={form} setForm={setForm} close={() => setDetailsOpen(false)} />}
  </section>;
}

function SegmentDetailsStep({ form, setForm, onCancel, onNext, error }: any) {
  return <section className="segment-onboarding"><div className="segment-onboarding-card"><div className="eyebrow">Create a segment</div><h1>Start with the basics</h1><p>Name the audience so it is easy to identify later in Flows and Automations. Criteria are configured in the next step.</p>{error && <div className="alert error">{error}</div>}<label><span>Segment name</span><input autoFocus value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="Example: Active villa prospects" /></label><label><span>Description</span><textarea rows={4} value={form.description ?? ""} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Describe who belongs to this audience and how it will be used." /></label><label className="segment-active-toggle"><input type="checkbox" checked={form.isActive} onChange={event => setForm({ ...form, isActive: event.target.checked })} /><span><b>Active segment</b><small>Available to other Studio modules after saving.</small></span></label><footer><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={onNext}>Next: configure criteria →</button></footer></div></section>;
}

function SegmentDetailsModal({ form, setForm, close }: any) {
  const [draft, setDraft] = useState({ name: form.name, description: form.description ?? "", isActive: form.isActive });
  return <div className="segment-modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><section className="segment-details-modal" role="dialog" aria-modal="true" aria-labelledby="segment-details-title"><header><div><div className="eyebrow">Segment settings</div><h2 id="segment-details-title">Edit details</h2></div><button className="expression-remove" onClick={close}>×</button></header><label><span>Name</span><input value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} /></label><label><span>Description</span><textarea rows={4} value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></label><label className="segment-active-toggle"><input type="checkbox" checked={draft.isActive} onChange={event => setDraft({ ...draft, isActive: event.target.checked })} /><span><b>Active segment</b><small>Allow this segment to be selected by other modules.</small></span></label><footer><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!draft.name.trim()} onClick={() => { setForm({ ...form, ...draft }); close(); }}>Apply changes</button></footer></section></div>;
}

function normalizeSide(value: any) { return { ...value, fields: value.fields ?? [], collections: value.collections ?? [], groupBy: value.groupBy ?? [], filters: normalizeGroup(value.filters), having: normalizeGroup(value.having), joins: (value.joins ?? []).map((join: any) => ({ ...join, conditions: normalizeGroup(join.conditions) })) }; }
function Heading({ number, title, action }: { number: string; title: string; action?: React.ReactNode }) { return <div className="studio-panel-head"><div className="segment-title"><i>{number}</i><h2>{title}</h2></div>{action}</div>; }

function ExpressionGroup({ value, aliases, fields, onChange, emptyText, depth = 0 }: { value: Group; aliases: any[]; fields: (alias: string) => Field[]; onChange: (value: Group) => void; emptyText?: string; depth?: number }) {
  const update = (index: number, item: Leaf | Group) => onChange({ ...value, items: value.items.map((current, itemIndex) => itemIndex === index ? item : current) });
  const remove = (index: number) => onChange({ ...value, items: value.items.filter((_, itemIndex) => itemIndex !== index) });
  return <div className={`expression-group depth-${Math.min(depth, 3)}`}>
    <header><div><span>{depth ? "Nested group" : "Condition logic"}</span><Select compact value={value.logic} options={[{ value: "AND", label: "Match all (AND)" }, { value: "OR", label: "Match any (OR)" }]} onChange={logic => onChange({ ...value, logic: logic as "AND" | "OR" })} /></div><div className="expression-actions"><button type="button" className="secondary" onClick={() => onChange({ ...value, items: [...value.items, leaf()] })}>+ Condition</button><button type="button" className="secondary" onClick={() => onChange({ ...value, items: [...value.items, group([leaf()])] })}>+ Group</button></div></header>
    {!value.items.length && <div className="empty-state compact">{emptyText ?? "Add the first condition or a nested group."}</div>}
    <div className="expression-items">{value.items.map((item, index) => <div className="expression-item" key={index}>{index > 0 && <div className="expression-connector"><span>{value.logic}</span></div>}{item.kind === "GROUP" ? <div className="nested-expression"><button type="button" className="expression-remove" aria-label="Remove nested group" onClick={() => remove(index)}>×</button><ExpressionGroup value={item} aliases={aliases} fields={fields} onChange={next => update(index, next)} depth={depth + 1} /></div> : <div className="expression-condition"><ConditionRow row={item} aliases={aliases} fields={fields} onChange={next => update(index, next)} /><button type="button" className="expression-remove" aria-label="Remove condition" onClick={() => remove(index)}>×</button></div>}</div>)}</div>
  </div>;
}

function ConditionRow({ row, aliases, fields, onChange }: { row: Leaf; aliases: any[]; fields: (alias: string) => Field[]; onChange: (value: Leaf) => void }) {
  const metadata = fields(row.leftAlias).find(field => field.name === row.leftField); const set = (patch: Partial<Leaf>) => onChange({ ...row, ...patch }); const aliasesAsOptions = aliases.map(alias => ({ value: alias.id, label: alias.label })); const availableOperators = options(operators[metadata?.type ?? "string"] ?? operators.string); const transformations = filterFunctions[metadata?.type ?? "string"] ?? filterFunctions.string; const selectedTransformation = transformations.find(item => item.value === (row.leftTransform ?? "NONE"));
  let valueControl: React.ReactNode = null;
  if (row.rightKind === "VALUE" && !["IS_NULL", "IS_NOT_NULL"].includes(row.operator)) {
    if (row.operator === "BETWEEN") valueControl = <div className="between-values"><input type={metadata?.type === "date" ? "datetime-local" : "number"} value={row.value} onChange={event => set({ value: event.target.value })} /><span>and</span><input type={metadata?.type === "date" ? "datetime-local" : "number"} value={row.valueTo ?? ""} onChange={event => set({ valueTo: event.target.value })} /></div>;
    else if (["IN_LAST", "NOT_IN_LAST"].includes(row.operator)) valueControl = <div className="relative-date-value"><input type="number" min="1" value={row.value} onChange={event => set({ value: event.target.value })} placeholder="Amount" /><Select value={row.relativeUnit ?? "DAYS"} options={options(["MINUTES", "HOURS", "DAYS", "WEEKS", "MONTHS", "YEARS"])} onChange={relativeUnit => set({ relativeUnit })} /></div>;
    else if (metadata?.type === "boolean") valueControl = <Select value={row.value} options={[{ value: "true", label: "True" }, { value: "false", label: "False" }]} onChange={value => set({ value })} />;
    else if (metadata?.values?.length && ["IN", "NOT_IN"].includes(row.operator)) valueControl = <MultiSelect value={row.value} options={options(metadata.values)} onChange={value => set({ value })} />;
    else if (metadata?.values?.length) valueControl = <Select value={row.value} options={options(metadata.values)} onChange={value => set({ value })} />;
    else valueControl = <input type={metadata?.type === "date" ? "datetime-local" : metadata?.type === "number" ? "number" : "text"} value={row.value} placeholder={row.operator.includes("IN") ? "A, B, C" : "Enter value"} onChange={event => set({ value: event.target.value })} />;
  }
  return <div className="condition-builder">
    <section className="condition-expression condition-expression-left">
      <div className="condition-expression-title"><b>Left side</b><small>Field to evaluate</small></div>
      <div className="condition-expression-fields">
        <label><span>Object</span><Select value={row.leftAlias} options={aliasesAsOptions} onChange={leftAlias => set({ leftAlias, leftField: "", value: "" })} /></label>
        <label><span>Field</span><Select value={row.leftField} options={fields(row.leftAlias).map(field => ({ value: field.name, label: field.name }))} onChange={leftField => set({ leftField, leftTransform: "NONE", leftTransformArgument: "", operator: "EQUALS", value: "" })} /></label>
      </div>
      <div className="condition-function-row">
        <label><span>Optional field function</span><Select value={row.leftTransform ?? "NONE"} options={transformations} onChange={leftTransform => set({ leftTransform, leftTransformArgument: "" })} /></label>
        {selectedTransformation?.argument && <label><span>{selectedTransformation.argument}</span><input value={row.leftTransformArgument ?? ""} onChange={event => set({ leftTransformArgument: event.target.value })} /></label>}
      </div>
    </section>
    <section className="condition-operator">
      <span>Comparison</span>
      <Select value={row.operator} options={availableOperators} onChange={operator => set({ operator, value: "" })} />
    </section>
    <section className="condition-expression condition-expression-right">
      <div className="condition-expression-title"><b>Right side</b><small>Value to compare against</small></div>
      <label className="condition-source-type"><span>Compare against</span><Select value={row.rightKind} options={[{ value: "VALUE", label: "A fixed value" }, { value: "FIELD", label: "Another object's field" }]} onChange={rightKind => set({ rightKind: rightKind as "VALUE" | "FIELD" })} /></label>
      {row.rightKind === "FIELD" ? <div className="condition-expression-fields">
        <label><span>Object</span><Select value={row.rightAlias} options={aliasesAsOptions} onChange={rightAlias => set({ rightAlias, rightField: "" })} /></label>
        <label><span>Field</span><Select value={row.rightField} options={fields(row.rightAlias).map(field => ({ value: field.name, label: field.name }))} onChange={rightField => set({ rightField })} /></label>
      </div> : valueControl && <label className="condition-static-value"><span>Value</span>{valueControl}</label>}
      {row.rightKind === "VALUE" && ["IS_NULL", "IS_NOT_NULL"].includes(row.operator) && <div className="condition-no-value">This operator does not require a value.</div>}
    </section>
  </div>;
}

function LegacyConditionRow({ row, aliases, fields, onChange }: { row: Leaf; aliases: any[]; fields: (alias: string) => Field[]; onChange: (value: Leaf) => void }) {
  const metadata = fields(row.leftAlias).find(field => field.name === row.leftField); const set = (patch: Partial<Leaf>) => onChange({ ...row, ...patch });
  return <div className="condition-builder"><label><span>Object</span><Select value={row.leftAlias} options={aliases.map(alias => ({ value: alias.id, label: alias.label }))} onChange={leftAlias => set({ leftAlias, leftField: "", value: "" })} /></label><label><span>Field</span><Select value={row.leftField} options={fields(row.leftAlias).map(field => ({ value: field.name, label: field.name }))} onChange={leftField => set({ leftField, operator: "EQUALS", value: "" })} /></label><label><span>Operator</span><Select value={row.operator} options={options(operators[metadata?.type ?? "string"] ?? operators.string)} onChange={operator => set({ operator })} /></label><label><span>Compare with</span><Select value={row.rightKind} options={[{ value: "VALUE", label: "Static value" }, { value: "FIELD", label: "Another field" }]} onChange={rightKind => set({ rightKind: rightKind as "VALUE" | "FIELD" })} /></label>{row.rightKind === "FIELD" ? <><label><span>Object</span><Select value={row.rightAlias} options={aliases.map(alias => ({ value: alias.id, label: alias.label }))} onChange={rightAlias => set({ rightAlias, rightField: "" })} /></label><label><span>Field</span><Select value={row.rightField} options={fields(row.rightAlias).map(field => ({ value: field.name, label: field.name }))} onChange={rightField => set({ rightField })} /></label></> : !["IS_NULL", "IS_NOT_NULL"].includes(row.operator) && <label><span>Value</span>{metadata?.type === "boolean" ? <Select value={row.value} options={[{ value: "true", label: "True" }, { value: "false", label: "False" }]} onChange={value => set({ value })} /> : metadata?.values?.length ? <Select value={row.value} options={options(metadata.values)} onChange={value => set({ value })} /> : <input type={metadata?.type === "date" ? "datetime-local" : metadata?.type === "number" ? "number" : "text"} value={row.value} placeholder={row.operator.includes("IN") ? "A, B, C" : "Enter value"} onChange={event => set({ value: event.target.value })} />}</label>}</div>;
}

function SeparatedOutputFields({ current, contactPoints, aliases, fields, updateRow, updateSide }: any) {
  const [availableFunctions, setAvailableFunctions] = useState<Record<string, Array<{ value: string; label: string; argument?: string }>>>({});
  useEffect(() => { void studioRequest<any>("/segments/metadata").then(metadata => setAvailableFunctions(metadata.functions ?? {})); }, []);
  const grouped = current.fields.map((row: any, index: number) => ({ row, index })).filter(({ row }: any) => row.aggregate === "NONE");
  const aggregated = current.fields.map((row: any, index: number) => ({ row, index })).filter(({ row }: any) => row.aggregate !== "NONE");
  const addGrouped = () => updateSide({ fields: [...current.fields, { alias: "profile", field: "", aggregate: "NONE", outputName: `group_${grouped.length + 1}` }] });
  const addAggregate = () => updateSide({ fields: [...current.fields, { alias: "profile", field: "", aggregate: "COUNT", outputName: `metric_${aggregated.length + 1}` }] });
  const remove = (index: number) => updateSide({ fields: current.fields.filter((_: any, rowIndex: number) => rowIndex !== index) });
  const objectOptions = aliases.map((alias: any) => ({ value: alias.id, label: alias.label }));
  return <section className="studio-panel output-section">
    <Heading number="4" title="Fields available to Flows and Automations" />
    <p className="section-intro">Choose the dimensions used to group the audience, then add the calculations you need.</p>
    <div className="mandatory-output-fields"><b>Recipient fields · grouped automatically</b><span>Subscriber key</span>{contactPoints.includes("EMAIL") && <span>Email</span>}{(contactPoints.includes("PHONE") || contactPoints.includes("WHATSAPP")) && <span>Phone</span>}</div>
    <div className="segment-output-block">
      <header><div><h3>Fields to group by</h3><p>One result row is produced for each unique combination of these fields.</p></div><button className="secondary" onClick={addGrouped}>+ Group field</button></header>
      {!grouped.length && <div className="empty-state compact">No grouping field selected.</div>}
      {grouped.map(({ row, index }: any) => <div className="segment-output-row" key={index}>
        <label><span>Object</span><Select value={row.alias} options={objectOptions} onChange={alias => updateRow("fields", index, { alias, field: "" })} /></label>
        <label><span>Field</span><Select value={row.field} options={fields(row.alias).map((field: Field) => ({ value: field.name, label: field.name }))} onChange={field => updateRow("fields", index, { field })} /></label>
        <TransformControl row={row} metadata={fields(row.alias).find((field: Field) => field.name === row.field)} functions={availableFunctions} update={(patch: any) => updateRow("fields", index, patch)} />
        <label><span>Output name</span><input value={row.outputName} onChange={event => updateRow("fields", index, { outputName: event.target.value })} placeholder="Example: country" /></label>
        <button className="expression-remove" onClick={() => remove(index)}>×</button>
      </div>)}
    </div>
    <div className="segment-output-block">
      <header><div><h3>Aggregated fields</h3><p>Calculate counts, totals, averages, minimums or maximums for each group.</p></div><button className="secondary" onClick={addAggregate}>+ Aggregated field</button></header>
      {!aggregated.length && <div className="empty-state compact">No aggregate calculation selected.</div>}
      {aggregated.map(({ row, index }: any) => { const metadata = fields(row.alias).find((field: Field) => field.name === row.field); return <div className="segment-output-row aggregate" key={index}>
        <label><span>Object</span><Select value={row.alias} options={objectOptions} onChange={alias => updateRow("fields", index, { alias, field: "" })} /></label>
        <label><span>Field</span><Select value={row.field} options={fields(row.alias).map((field: Field) => ({ value: field.name, label: field.name }))} onChange={field => updateRow("fields", index, { field })} /></label>
        <TransformControl row={row} metadata={metadata} functions={availableFunctions} update={(patch: any) => updateRow("fields", index, patch)} />
        <label><span>Aggregate function</span><Select value={row.aggregate} options={options(["COUNT", "COUNT_DISTINCT", ...(metadata?.type === "number" ? ["SUM", "AVG"] : []), "MIN", "MAX"])} onChange={aggregate => updateRow("fields", index, { aggregate })} /></label>
        <label><span>Output name</span><input value={row.outputName} onChange={event => updateRow("fields", index, { outputName: event.target.value })} placeholder="Example: totalVisits" /></label>
        <button className="expression-remove" onClick={() => remove(index)}>×</button>
      </div>; })}
    </div>
    <RelatedCollections current={current} aliases={aliases.filter((alias: any) => alias.id !== "profile")} fields={fields} updateSide={updateSide} />
    <div className="having-head"><b>HAVING conditions</b><small>Filter the calculated results after aggregation.</small></div>
    <HavingGroup value={normalizeGroup(current.having)} fields={aggregated.map(({ row }: any) => row)} onChange={having => updateSide({ having })} />
  </section>;
}

function TransformControl({ row, metadata, functions, update }: any) {
  const choices = functions[metadata?.type ?? "string"] ?? [{ value: "NONE", label: "No transformation" }];
  const selected = choices.find((item: any) => item.value === (row.transform ?? "NONE"));
  return <><label><span>Field function</span><Select value={row.transform ?? "NONE"} options={choices} onChange={transform => update({ transform, transformArgument: "" })} /></label>{selected?.argument && <label><span>{selected.argument}</span><input value={row.transformArgument ?? ""} onChange={event => update({ transformArgument: event.target.value })} placeholder={selected.argument} /></label>}</>;
}

function RelatedCollections({ current, aliases, fields, updateSide }: any) {
  const collections = current.collections ?? [];
  const update = (index: number, patch: any) => updateSide({ collections: collections.map((item: any, itemIndex: number) => itemIndex === index ? { ...item, ...patch } : item) });
  const remove = (index: number) => updateSide({ collections: collections.filter((_: any, itemIndex: number) => itemIndex !== index) });
  const add = () => { const alias = aliases[0]?.id ?? ""; updateSide({ collections: [...collections, { name: `relatedRecords${collections.length + 1}`, alias, dedupeField: "", fields: [] }] }); };
  return <div className="segment-output-block collection-builder">
    <header><div><h3>Related records collections</h3><p>Create a reusable, deduplicated list for repeated email content. No JSON or scripting is required.</p></div><button className="secondary" disabled={!aliases.length} onClick={add}>+ Related collection</button></header>
    {!aliases.length && <div className="empty-state compact">Join a related object first, then create a collection from it.</div>}
    {collections.map((collection: any, index: number) => { const available = fields(collection.alias); return <article className="collection-card" key={index}>
      <div className="collection-main-row">
        <label><span>Collection name</span><input value={collection.name} onChange={event => update(index, { name: event.target.value })} placeholder="Example: visitedVillas" /></label>
        <label><span>Related object</span><Select value={collection.alias} options={aliases.map((alias: any) => ({ value: alias.id, label: alias.label }))} onChange={alias => update(index, { alias, dedupeField: "", fields: [] })} /></label>
        <label><span>Remove duplicates using</span><Select value={collection.dedupeField} options={available.map((field: Field) => ({ value: field.name, label: field.name }))} onChange={dedupeField => update(index, { dedupeField })} /></label>
        <button className="expression-remove" onClick={() => remove(index)}>×</button>
      </div>
      <div className="collection-fields"><b>Fields available in each repeated item</b>{available.map((field: Field) => <label key={field.name}><input type="checkbox" checked={(collection.fields ?? []).includes(field.name)} onChange={event => update(index, { fields: event.target.checked ? [...(collection.fields ?? []), field.name] : (collection.fields ?? []).filter((name: string) => name !== field.name) })} /><span>{field.name}</span></label>)}</div>
    </article>; })}
  </div>;
}

function OutputFieldsSection({ current, aliases, fields, updateRow, updateSide }: any) {
  const addField = () => updateSide({ fields: [...current.fields, { alias: "profile", field: "", aggregate: "NONE", outputName: `field_${current.fields.length + 1}` }] });
  return <section className="studio-panel output-section"><Heading number="4" title="Fields available to Flows and Automations" action={<button className="secondary" onClick={addField}>+ Select field</button>} /><p className="section-intro">Choose every value the segment should expose later, such as order date, chat creation date, product, source or calculated totals. Subscriber key and contact points are included automatically.</p>{!current.fields.length && <button className="output-empty" onClick={addField}><b>Select the data this segment should provide</b><span>Add fields from the profile or any joined object.</span></button>}{current.fields.map((row: any, index: number) => { const metadata = fields(row.alias).find((field: Field) => field.name === row.field); const grouped = current.groupBy.some((item: any) => item.alias === row.alias && item.field === row.field); return <div className="output-row" key={index}><label><span>Object</span><Select value={row.alias} options={aliases.map((alias: any) => ({ value: alias.id, label: alias.label }))} onChange={alias => updateRow("fields", index, { alias, field: "" })} /></label><label><span>Field</span><Select value={row.field} options={fields(row.alias).map((field: Field) => ({ value: field.name, label: field.name }))} onChange={field => updateRow("fields", index, { field, aggregate: "NONE" })} /></label><label><span>Calculation</span><Select value={row.aggregate} options={options(["NONE", "COUNT", "COUNT_DISTINCT", ...(metadata?.type === "number" ? ["SUM", "AVG"] : []), "MIN", "MAX"])} onChange={aggregate => updateRow("fields", index, { aggregate })} /></label><label><span>Output name</span><input value={row.outputName} onChange={event => updateRow("fields", index, { outputName: event.target.value })} placeholder="Example: lastChatDate" /></label><label className="studio-check output-group"><input type="checkbox" disabled={!row.field || row.aggregate !== "NONE"} checked={grouped} onChange={event => updateSide({ groupBy: event.target.checked ? [...current.groupBy, { alias: row.alias, field: row.field }] : current.groupBy.filter((item: any) => item.alias !== row.alias || item.field !== row.field) })} /> Group by</label><button className="expression-remove" onClick={() => updateSide({ fields: current.fields.filter((_: any, rowIndex: number) => rowIndex !== index) })}>×</button></div>; })}<div className="having-head"><b>HAVING conditions</b><small>Available when an output field uses an aggregate calculation.</small></div><HavingGroup value={normalizeGroup(current.having)} fields={current.fields.filter((field: any) => field.aggregate !== "NONE")} onChange={having => updateSide({ having })} /></section>;
}

function OutputSection({ current, aliases, fields, updateRow, updateSide }: any) {
  return <section className="studio-panel"><Heading number="4" title="Output, grouping & HAVING" action={<button className="secondary" onClick={() => updateSide({ fields: [...current.fields, { alias: "profile", field: "", aggregate: "NONE", outputName: `field_${current.fields.length + 1}` }] })}>+ Output field</button>} />{current.fields.map((row: any, index: number) => { const metadata = fields(row.alias).find((field: Field) => field.name === row.field); const grouped = current.groupBy.some((item: any) => item.alias === row.alias && item.field === row.field); return <div className="output-row" key={index}><Select value={row.alias} options={aliases.map((alias: any) => ({ value: alias.id, label: alias.label }))} onChange={alias => updateRow("fields", index, { alias, field: "" })} /><Select value={row.field} options={fields(row.alias).map((field: Field) => ({ value: field.name, label: field.name }))} onChange={field => updateRow("fields", index, { field, aggregate: "NONE" })} /><Select value={row.aggregate} options={options(["NONE", "COUNT", "COUNT_DISTINCT", ...(metadata?.type === "number" ? ["SUM", "AVG"] : []), "MIN", "MAX"])} onChange={aggregate => updateRow("fields", index, { aggregate })} /><input value={row.outputName} onChange={event => updateRow("fields", index, { outputName: event.target.value })} placeholder="Output name" /><label className="studio-check"><input type="checkbox" disabled={!row.field || row.aggregate !== "NONE"} checked={grouped} onChange={event => updateSide({ groupBy: event.target.checked ? [...current.groupBy, { alias: row.alias, field: row.field }] : current.groupBy.filter((item: any) => item.alias !== row.alias || item.field !== row.field) })} /> Group</label><button className="expression-remove" onClick={() => updateSide({ fields: current.fields.filter((_: any, rowIndex: number) => rowIndex !== index) })}>×</button></div>; })}<div className="having-head"><b>HAVING conditions</b><small>Nested conditions are supported after adding an aggregate output.</small></div><HavingGroup value={normalizeGroup(current.having)} fields={current.fields.filter((field: any) => field.aggregate !== "NONE")} onChange={having => updateSide({ having })} /></section>;
}

function HavingGroup({ value, fields, onChange, depth = 0 }: { value: Group; fields: any[]; onChange: (value: Group) => void; depth?: number }) {
  const update = (index: number, item: any) => onChange({ ...value, items: value.items.map((current: any, itemIndex: number) => itemIndex === index ? item : current) }); const remove = (index: number) => onChange({ ...value, items: value.items.filter((_: any, itemIndex: number) => itemIndex !== index) });
  return <div className={`expression-group having-group depth-${Math.min(depth, 3)}`}><header><Select compact value={value.logic} options={[{ value: "AND", label: "Match all (AND)" }, { value: "OR", label: "Match any (OR)" }]} onChange={logic => onChange({ ...value, logic })} /><div className="expression-actions"><button className="secondary" disabled={!fields.length} onClick={() => onChange({ ...value, items: [...value.items, { kind: "CONDITION", field: "", operator: "GT", value: "0" }] })}>+ Condition</button><button className="secondary" disabled={!fields.length} onClick={() => onChange({ ...value, items: [...value.items, group([{ kind: "CONDITION", field: "", operator: "GT", value: "0" } as Leaf])] })}>+ Group</button></div></header>{value.items.map((item: any, index: number) => <div className="expression-item" key={index}>{index > 0 && <div className="expression-connector"><span>{value.logic}</span></div>}{item.kind === "GROUP" ? <div className="nested-expression"><button className="expression-remove" onClick={() => remove(index)}>×</button><HavingGroup value={item} fields={fields} onChange={(next: any) => update(index, next)} depth={depth + 1} /></div> : <div className="having-condition"><Select value={item.field} options={fields.map((field: any) => ({ value: field.outputName, label: field.outputName }))} onChange={field => update(index, { ...item, field })} /><Select value={item.operator} options={options(["EQUALS", "NOT_EQUALS", "GT", "GTE", "LT", "LTE"])} onChange={operator => update(index, { ...item, operator })} /><input type="number" value={item.value} onChange={event => update(index, { ...item, value: event.target.value })} /><button className="expression-remove" onClick={() => remove(index)}>×</button></div>}</div>)}</div>;
}

function PreviewPanel({ data, value, onChange, run, page }: any) { const output = data?.output ?? [{ name: "subscriberKey" }]; const previewFields = (_alias: string) => output.filter((item: any) => item.type !== "collection").map((item: any) => ({ name: item.name, type: item.type ?? "string" })); const aliases = [{ id: "result", label: "Preview result" }]; const adapted = adaptPreviewGroup(value); return <section className="studio-panel"><div className="studio-panel-head"><div><h2>Audience preview</h2><p>These nested filters affect the preview only.</p></div></div><ExpressionGroup value={adapted} aliases={aliases} fields={previewFields} onChange={next => onChange(stripPreviewGroup(next))} /><button className="primary segment-apply" onClick={() => run(1)}>Apply filters</button>{data && <><div className="preview-total">{data.total.toLocaleString()} matching profiles</div><div className="tablewrap"><table><thead><tr>{output.map((item: any) => <th key={item.name}>{item.name}</th>)}</tr></thead><tbody>{data.items.map((row: any, index: number) => <tr key={index}>{output.map((item: any) => <td key={item.name}>{item.type === "collection" ? <CollectionPreview value={row[item.name]} /> : String(row[item.name] ?? "—")}</td>)}</tr>)}</tbody></table></div><div className="pagination"><button disabled={page <= 1} onClick={() => run(page - 1)}>Previous</button><span>Page {page} of {data.pages}</span><button disabled={page >= data.pages} onClick={() => run(page + 1)}>Next</button></div><details className="generated-sql"><summary>Generated SQL</summary><pre>{data.generatedSql}</pre></details></>}</section>; }
function CollectionPreview({ value }: { value: unknown }) { const items = Array.isArray(value) ? value : []; return <details className="collection-preview"><summary>{items.length} related record{items.length === 1 ? "" : "s"}</summary>{items.map((item: any, index: number) => <div key={index}>{Object.entries(item).map(([key, fieldValue]) => <span key={key}><b>{key}</b>{String(fieldValue ?? "—")}</span>)}</div>)}</details>; }
function adaptPreviewGroup(value: Group): Group { return { ...value, items: value.items.map((item: any) => item.kind === "GROUP" ? adaptPreviewGroup(item) : ({ ...item, leftAlias: "result", leftField: item.field ?? item.leftField ?? "subscriberKey" })) }; }
function stripPreviewGroup(value: Group): Group { return { ...value, items: value.items.map((item: any) => item.kind === "GROUP" ? stripPreviewGroup(item) : ({ kind: "CONDITION", field: item.leftField, operator: item.operator, value: item.value, valueTo: item.valueTo, relativeUnit: item.relativeUnit } as any)) }; }
